"""Step 3: apply the hand review (review1-5.py) to auto.json and write freq-table.js,
the block that sits between the FREQ-TABLE markers in hebrew-reader.html.

    node extract.js ../../hebrew-reader.html appkeys.json
    python match.py
    python build.py
    python splice.py        # replaces the block in hebrew-reader.html

Source list: Juan Pinto, Frequency Dictionary of Spoken Hebrew (OpenSubtitles 2018),
MIT licence, github.com/juandpinto/frequency-dictionary — fdosh.tsv here.
"""
import json, re, sys, io, os, importlib
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
S = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, S)
app = json.load(open(os.path.join(S, "appkeys.json"), encoding='utf-8'))
auto = json.load(open(os.path.join(S, "auto.json"), encoding='utf-8'))
html = open(os.path.join(S, "..", "..", "hebrew-reader.html"), encoding='utf-8').read()
m = re.search(r"const STOPLIST = new Set\(\[(.*?)\]\);", html, re.S)
STOP = set(re.findall(r'"([^"]+)"', m.group(1)))

OV, NEW = {}, {}
for i in range(1, 6):
    mod = importlib.import_module('review%d' % i)
    for k, v in mod.OV.items():
        if k in OV and OV[k] != v: print('conflicting override', k)
        OV[k] = v
    NEW.update(mod.NEW)

LIMIT = 3000
# A finite form ("I thought", "you did") is one conjugation of a word, not the word.
INFLECTED = re.compile(r"^(I |I will|you will|you |we |he |she |they |it/he|he/it)")
claimed, entries, used_new = set(), [], {}
for rank, lem, hit in auto:
    if rank > LIMIT: break
    keys = OV[rank] if rank in OV else hit
    if not keys: continue
    out = []
    for k in keys:
        if k in STOP or k in claimed: continue
        if k in app:
            if INFLECTED.match(app[k]['en']): continue
        elif k in NEW:
            used_new[k] = NEW[k]
        else:
            print('UNKNOWN KEY', rank, lem, k); continue
        out.append(k)
    if not out: continue
    claimed.update(out)
    entries.append((rank, lem, out))

# A new key that looks like prefix + an existing word changes how sentences resolve:
# libKeyFor tries the exact key before peeling. Each of these was checked by hand.
PFX = 'והבלמשכ'
for k in used_new:
    for n in (1, 2):
        rest = k[n:]
        if len(k) > n + 1 and all(c in PFX for c in k[:n]) and rest in app:
            print('prefix-overlap:', k, '->', rest, app[rest]['en'])

print('entries', len(entries), 'new glosses', len(used_new))
print('1000th lemma is FDOSH rank', entries[999][0] if len(entries) >= 1000 else '(short)')

def js_str(x): return json.dumps(x, ensure_ascii=False)
cat = lambda en: "Verbs" if en.startswith("to ") else "Uncategorised"
lst = " ".join("|".join(keys) for _, _, keys in entries)
lines, line = [], ""
for p in lst.split(" "):
    if line and len(line) + len(p) + 1 > 96:
        lines.append(line); line = p
    else:
        line = (line + " " + p) if line else p
lines.append(line)
body = " +\n".join('  "' + l + (' ' if i < len(lines) - 1 else '') + '"' for i, l in enumerate(lines))
rows, row = [], []
for k, (tr, en) in used_new.items():
    row.append(js_str(k) + ":[" + js_str(tr) + "," + js_str(en) + "," + js_str(cat(en)) + "]")
    if len(row) == 3: rows.append("  " + ",".join(row)); row = []
if row: rows.append("  " + ",".join(row))
out = ("/* FREQ-TABLE-BEGIN — generated by tools/freq/build.py. Edit the review files there\n"
       "   and rebuild; hand edits here are overwritten. */\n"
       "const FREQ_LIST =\n" + body + ";\n"
       "const FREQ_DICT = {\n" + ",\n".join(rows) + "\n};\n"
       "/* FREQ-TABLE-END */\n")
open(os.path.join(S, "freq-table.js"), "w", encoding="utf-8", newline="\n").write(out)
print("wrote freq-table.js,", len(out.encode('utf-8')), "bytes")
