# FDOSH ranks 301-600
D = None
OV = {
  302: ['לשחק', 'משחק'],
  305: D, 313: D, 317: D, 320: D, 324: D, 328: D, 333: ['להתראות'], 356: D, 362: D, 363: ['בחייך'],
  366: D, 372: D, 376: D, 377: D, 378: D, 386: D, 389: D, 401: ['מיד'], 407: D, 412: D,
  415: D, 418: D, 420: D, 422: D, 424: D, 427: D, 428: D, 431: D, 433: D, 440: D, 443: D,
  449: D, 451: D, 454: D, 457: D, 466: D, 467: D, 468: D, 474: D, 479: D, 480: D, 489: D,
  490: D, 503: D, 504: D, 508: D, 512: D, 516: D, 529: D, 536: D, 543: D, 546: D, 548: D,
  551: D, 553: D, 560: D, 570: D, 574: D, 580: D, 581: D, 582: D, 585: D, 588: D, 590: D,
  594: D, 600: D, 324: D, 354: D, 357: D,
  306: ['אחי'],
  326: ['להשאיר', 'משאיר'],
  329: ['להוציא', 'מוציא'],
  332: ['לסיים', 'מסיים', 'סיים'],
  336: ['למעשה'], 340: ['כאשר'],
  343: ['להבטיח', 'מבטיח'],
  344: ['חסר'],
  361: ['לפגוע', 'פוגע'],
  368: ['יושב', 'לשבת'],
  391: ['למעלה'], 392: ['מושג'],
  397: ['לסלוח', 'סלח'],
  411: ['סיכוי'],
  413: ['לנצח'],
  414: ['להציל'],
  421: ['כאב', 'כואב'],
  430: ['כלומר'], 429: ['אדיר'],
  442: ['שיחה'],
  446: ['נורא'], 453: ['שאר'],
  462: ['לתפוס', 'תופס'],
  470: ['לטפל', 'מטפל'],
  473: ['מסוגל'], 476: ['שקט'],
  501: ['יכולת'], 514: ['מצחיק'], 517: ['בגד', 'בגדים'], 519: ['שווה'], 520: ['קטע'],
  522: ['עלול'],
  537: ['מצפה'],
  552: ['בדיקה'], 555: ['עובדה'], 559: ['זז', 'לזוז'], 561: ['מעט'], 568: ['קיים'],
  571: ['זקוק'], 572: ['בחורה'], 578: ['מחדש'], 583: ['הלו'], 591: ['בתור'],
  598: ['צוחק', 'לצחוק'],
}
NEW = {
  'אחי': ('akhi', 'bro / my brother'),
  'להשאיר': ('lehash\'ir', 'to leave (something)'),
  'משאיר': ('mash\'ir', 'leave(s) (something) (m)'),
  'להוציא': ('lehotzi', 'to take out / spend'),
  'מוציא': ('motzi', 'take(s) out / spend(s) (m)'),
  'מסיים': ('mesayem', 'finish(es) (m)'),
  'למעשה': ('lema\'ase', 'actually / in fact'),
  'כאשר': ('ka\'asher', 'when (formal)'),
  'להבטיח': ('lehavti\'akh', 'to promise'),
  'מבטיח': ('mavti\'akh', 'promise(s) (m)'),
  'חסר': ('khaser', 'missing / lacking'),
  'לפגוע': ('lifgo\'a', 'to hurt / hit'),
  'פוגע': ('poge\'a', 'hurt(s) / hit(s) (m)'),
  'בחייך': ('bekhayekh', 'come on! (lit. on your life)'),
  'למעלה': ('lemala', 'up / upstairs'),
  'מושג': ('musag', 'idea / notion (אין לי מושג = no idea)'),
  'לסלוח': ('lislo\'akh', 'to forgive'),
  'סלח': ('slakh', 'forgive! (סלח לי = excuse me)'),
  'מיד': ('miyad', 'immediately'),
  'סיכוי': ('sikui', 'chance'),
  'להציל': ('lehatzil', 'to save / rescue'),
  'כלומר': ('kl\'omar', 'that is / I mean'),
  'אדיר': ('adir', 'awesome / mighty'),
  'נורא': ('nora', 'terrible / terribly'),
  'שאר': ('she\'ar', 'rest (the rest of)'),
  'לתפוס': ('litpos', 'to catch'),
  'תופס': ('tofes', 'catch(es) (m)'),
  'לטפל': ('letapel', 'to take care of / treat'),
  'מטפל': ('metapel', 'take(s) care of (m)'),
  'מסוגל': ('mesugal', 'capable / able (m)'),
  'שקט': ('sheket', 'quiet'),
  'יכולת': ('yekholet', 'ability'),
  'מצחיק': ('matzkhik', 'funny'),
  'בגד': ('beged', 'garment / piece of clothing'),
  'שווה': ('shave', 'worth / equal'),
  'קטע': ('keta', 'bit / thing / scene'),
  'עלול': ('alul', 'might / liable to (m)'),
  'בדיקה': ('bdika', 'test / check'),
  'עובדה': ('uvda', 'fact'),
  'זז': ('zaz', 'move(s) (m)'),
  'לזוז': ('lazuz', 'to move'),
  'מעט': ('me\'at', 'a little / few'),
  'קיים': ('kayam', 'exist(s) (m)'),
  'זקוק': ('zakuk', 'in need of (m)'),
  'בחורה': ('bakhura', 'girl / young woman'),
  'מחדש': ('mekhadash', 'again / anew'),
  'הלו': ('halo', 'hello (on the phone)'),
  'בתור': ('betor', 'as (a)'),
  'צוחק': ('tzokhek', 'laugh(s) (m) / joking'),
  'לצחוק': ('litzkhok', 'to laugh'),
}
